
name: Build Develop Bothub-NLP-API Image
on:
  push:
    tags:
      - 'develop-v*.*.*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: bothubit/bothub-nlp-api:${{ steps.vars.outputs.tag }}
          build-args: |
            ENVIRONMENT='development'
            GIT_BRANCH='develop'
            GIT_URL='https://github.com/bothub-it/bothub-nlp-api.git'
            PORTAINER_URL='https://portainer-development.bothub.it/'
            PORTAINER_STACK_ID='11'
            PORTAINER_ENDPOINT_ID='2'
            TRAEFIK_BASE_URL='nlp-development.bothub.it'
